#! /bin/bash

# We read the number of ensembles and subdomains from the configuration file
file=$(pwd)"/cwipiConfig"

while read -r name num
do
    if
    [[ $name == "cwipiMembers" ]]; then
     printf -v ensembles "%s\n" "$num"
    fi
done < $file

echo 'The number of ensembles we are dealing with is' $ensembles |sed 's/= //'
cwipiMembers=$(printf "%s" "$ensembles" |sed 's/= //')

while read -r name num
do
    if
    [[ $name == "subDomains" ]]; then
     printf -v subdomains "%s\n" "$num"
    fi
done < $file

echo 'The number of decompositions we are dealing with is' $subdomains |sed 's/= //'
cwipiDec=$(printf "%s" "$subdomains" |sed 's/= //')
# echo $cwipiMembers

# We run the mesh
# blockMesh

# We decompose the domain in the 1st ensemble
decomposePar -force

rm -rf results postProcessing log
mkdir -p $(pwd)/results

for ((j=0; j<cwipiDec; j++));
do
    cp -r system processor$j/
done

# We create the "processor" folders with all information they need
for ((i=0; i<(cwipiMembers-1); i++));
do 
    for ((j=0; j<cwipiDec; j++));
    do
    	let k=cwipiDec*i+cwipiDec+j
    	mkdir -p $(pwd)/processor$k
    	cp -r processor$j/0/ processor$k/
    	cp -r processor$j/constant/ processor$k/
    	cp -r processor$j/system/ processor$k/
    done
    
    let even=2*i+2
    let odd=2*i+3
    echo $even
    echo $odd
    sed -i -e "s/procBoundary0/procBoundary$even/g" processor$even/0/U
    sed -i -e "s/to1/to$odd/g" processor$even/0/U
    sed -i -e "s/procBoundary1/procBoundary$odd/g" processor$odd/0/U
    sed -i -e "s/to0/to$even/g" processor$odd/0/U
done

for ((i=0; i<cwipiMembers; ++i));
do
    l=$(echo "$i 1.0 $cwipiMembers" | awk '{printf "%3.1f", ($1+$2)/$3}' |tr ',' '.')
    echo $l
    for ((j=0; j<cwipiDec; ++j));
    do
    	let m=cwipiDec*i+j
    	sed -i -e "s/uniform (1/uniform ($l/g" processor$m/0/U
    done
done

# We run in parallel with the number of ensembles wished
# mpirun -np 1 ./KF_coupling.exe : -np $cwipiMembers cwipiIcoFoam -parallel | tee log
