#! /bin/bash

# We read the number of ensembles from the controlDict
file=$(pwd)"/cwipiConfig"

while read -r name num
do
    if
    [[ $name == "cwipiMembers" ]]; then
     printf -v ensembles "%s\n" "$num"
    fi
done < $file

echo 'The number of ensembles we are dealing with is' $ensembles |sed 's/= //'
cwipiMembers=$(printf "%s" "$ensembles" |sed 's/= //')
# echo $cwipiMembers

# We run the mesh
# blockMesh

mkdir results
# We create the "processor" folders with all information they need
for ((i=0; i<cwipiMembers; i++));
do 
    mkdir -p $(pwd)/processor$i
    cp -r 0/ processor$i/
    cp -r constant/ processor$i/
    cp -r system/ processor$i/
    j=$(echo "$i 1.0 $cwipiMembers" | awk '{printf "%3.1f", ($1+$2)/$3}' |tr ',' '.')
    echo $j
    sed -i -e "s/uniform (1/uniform ($j/g" processor$i/0/U
done

# We run in parallel with the number of ensembles wished
mpirun -np 1 ./KF_coupling.exe : -np $cwipiMembers cwipiIcoFoam -parallel | tee log
